import { StageDefinition, ActiveStudent, StudentJourney, AdminCredentials } from './types';

export const PEGANGAN_DI_SEPANJANG_JALAN =
  'Percaya diri bukan bakat yang dimiliki sejak lahir. Ia tumbuh setiap kali kamu berani mencoba sekali lagi.';

export const PESAN_UNTUK_DIRI_SAYA =
  'Bukan karena mudah lalu saya berani. Karena saya berani, lama-lama menjadi mudah.';

export const STAGES_DATA: StageDefinition[] = [
  {
    id: 1,
    title: 'Potret percaya diri saya',
    subtitle: 'Titik mulai',
    sectionTag: 'Titik mulai',
    etapeNumber: 1,
    etapeTitle: 'Etape 1: Mengenali diri dan menghadapi tantangan',
    theme: 'Lembah Pengenalan Diri',
    islandName: 'Puncak Percaya Diri',
    meetingPhase: 1,
    color: 'emerald',
    badgeName: 'Berani Memulai',
    badgeIcon: 'Compass',
    missionDescription:
      'Petakan situasi di mana kamu merasa kurang percaya diri, apa yang kamu pikirkan, rasakan, dan tindakan yang kamu ambil.',
    motivationalQuote: PEGANGAN_DI_SEPANJANG_JALAN,
    exampleText:
      'Saya tahu jawabannya, tapi tangan saya tidak pernah terangkat saat guru bertanya.',
    fields: [
      {
        id: 'situation',
        label: 'Di situasi apa saya merasa kurang percaya diri?',
        type: 'textarea',
        placeholder: 'Contoh: Saat disuruh berbicara di depan kelas atau saat guru bertanya...',
      },
      {
        id: 'thought',
        sectionHeader: 'Saat situasi itu terjadi:',
        label: 'Saya berpikir:',
        type: 'textarea',
        placeholder: 'Apa yang terlintas dalam pikiranmu...',
      },
      {
        id: 'feeling',
        label: 'Saya merasa:',
        type: 'textarea',
        placeholder: 'Apa yang dirasakan tubuh dan hatimu (deg-degan, takut, dll)...',
      },
      {
        id: 'action',
        label: 'Saya lalu:',
        type: 'textarea',
        placeholder: 'Apa yang akhirnya kamu lakukan saat itu...',
      },
      {
        id: 'confidence_scale',
        label: 'Percaya diri saya hari ini ada di angka:',
        type: 'slider',
        min: 1,
        max: 5,
        step: 1,
        minLabel: 'Belum berani',
        maxLabel: 'Sangat berani',
        helperText: 'Skala 1 (Belum berani) sampai 5 (Sangat berani)',
      },
    ],
  },
  {
    id: 2,
    title: 'Tantangan yang saya pilih',
    subtitle: 'Challenge',
    sectionTag: 'Challenge',
    etapeNumber: 1,
    etapeTitle: 'Etape 1: Mengenali diri dan menghadapi tantangan',
    theme: 'Hutan Belantara Target',
    islandName: 'Tebing Tantangan',
    meetingPhase: 1,
    color: 'teal',
    badgeName: 'Penakluk Rintangan',
    badgeIcon: 'Mountain',
    missionDescription:
      'Pilihlah satu tantangan nyata yang paling ingin kamu taklukkan dan tukar kalimat keraguan menjadi kalimat bertumbuh.',
    motivationalQuote: PESAN_UNTUK_DIRI_SAYA,
    fields: [
      {
        id: 'challenge_target',
        label: 'Satu tantangan yang paling ingin saya taklukkan:',
        type: 'textarea',
        placeholder: 'Tuliskan tantangan belajarmu secara spesifik...',
      },
      {
        id: 'heavy_reason',
        label: 'Apa yang membuat terasa berat?',
        type: 'textarea',
        placeholder: 'Jelaskan mengapa tantangan ini terasa berat bagimu...',
      },
      {
        id: 'growth_learning_way',
        sectionHeader: "Tukar kalimatnya: dari 'Saya tidak bisa' menjadi 'Saya belum bisa'",
        label: '...dan saya sedang belajar dengan cara:',
        type: 'textarea',
        placeholder: 'Tuliskan caramu belajar menghadapi hal tersebut...',
      },
      {
        id: 'fear_motto',
        label: 'Kalimat untuk diri saya saat takut mencoba:',
        type: 'textarea',
        placeholder: 'Kalimat penyemangat pribadi saat rasa takut muncul...',
      },
    ],
  },
  {
    id: 3,
    title: 'Hambatan di jalan saya',
    subtitle: 'Obstacles',
    sectionTag: 'Obstacles',
    etapeNumber: 1,
    etapeTitle: 'Etape 1: Mengenali diri dan menghadapi tantangan',
    theme: 'Rawa-Rawa Keraguan',
    islandName: 'Goa Pembuka Rahasia',
    meetingPhase: 1,
    color: 'sky',
    badgeName: 'Mata Elang',
    badgeIcon: 'Eye',
    missionDescription:
      'Kenali hambatan dari dalam diri dan luar lingkungan, pahami alasannya, serta temukan cara melewatinya.',
    motivationalQuote: 'Menyadari hambatan adalah setengah jalan dari menemukan jalan keluar.',
    fields: [
      {
        id: 'internal_obstacles',
        sectionHeader: 'Hambatan dari dalam diri saya (pikiran, perasaan):',
        label: 'Tuliskan hambatan internal:',
        type: 'textarea',
        placeholder: 'Contoh: Takut salah, rasa cemas ditertawakan, suka menunda...',
      },
      {
        id: 'external_obstacles',
        sectionHeader: 'Hambatan dari luar (lingkungan, orang lain):',
        label: 'Tuliskan hambatan eksternal:',
        type: 'textarea',
        placeholder: 'Contoh: Godaan smartphone, suasana kelas berisik...',
      },
      {
        id: 'why_obstacle_arises',
        label: 'Mengapa hambatan itu muncul?',
        type: 'textarea',
        placeholder: 'Analisis penyebab di balik munculnya hambatan tersebut...',
      },
      {
        id: 'how_to_overcome',
        label: 'Cara saya melewatinya:',
        type: 'textarea',
        placeholder: 'Strategi konkret apa yang akan kamu lakukan...',
      },
      {
        id: 'giveup_motto',
        label: 'Kalimat untuk diri saya saat ingin menyerah:',
        type: 'textarea',
        placeholder: 'Pengingat untuk bangkit saat merasa ingin berhenti...',
      },
    ],
  },
  {
    id: 4,
    title: 'Langkah kecil saya',
    subtitle: 'Effort',
    sectionTag: 'Effort',
    etapeNumber: 1,
    etapeTitle: 'Etape 1: Mengenali diri dan menghadapi tantangan',
    theme: 'Jembatan Langkah Emas',
    islandName: 'Pondok Rencana Aksi',
    meetingPhase: 1,
    color: 'blue',
    badgeName: 'Arsitek Aksi',
    badgeIcon: 'Footprints',
    missionDescription:
      'Susun 3 langkah kecil menuju tantanganmu mulai dari yang paling mudah dan tentukan tanggal mulainya.',
    motivationalQuote: 'Kamu tidak perlu melihat seluruh anak tangga, cukup ambil langkah pertama.',
    fields: [
      {
        id: 'step_1',
        sectionHeader: 'Tiga langkah menuju tantangan saya, dari yang paling mudah:',
        label: '1. Langkah pertama (paling mudah):',
        type: 'text',
        placeholder: 'Langkah pertama yang paling ringan dan mudah dimulai...',
      },
      {
        id: 'step_2',
        label: '2. Langkah kedua:',
        type: 'text',
        placeholder: 'Langkah lanjutan...',
      },
      {
        id: 'step_3',
        label: '3. Langkah ketiga:',
        type: 'text',
        placeholder: 'Langkah ketiga...',
      },
      {
        id: 'start_date',
        sectionHeader: 'Rencana saya:',
        label: 'Mulai tanggal:',
        type: 'text',
        placeholder: 'Contoh: 20 September 2026 atau Mulai besok...',
      },
      {
        id: 'consistency_strategy',
        label: 'Agar konsisten:',
        type: 'text',
        placeholder: 'Contoh: Memasang alarm harian pukul 16.00...',
      },
      {
        id: 'helper_person',
        label: 'Yang membantu:',
        type: 'text',
        placeholder: 'Contoh: Teman sebangku, orang tua, guru BK...',
      },
      {
        id: 'step_done_motto',
        label: 'Kalimat untuk diri saya setiap selesai satu langkah:',
        type: 'textarea',
        placeholder: 'Apresiasi kepada diri sendiri setelah menyelesaikan satu langkah...',
      },
    ],
  },
  {
    id: 5,
    title: 'Saat saya dikritik',
    subtitle: 'Critiques',
    sectionTag: 'Critiques',
    etapeNumber: 2,
    etapeTitle: 'Etape 2: Belajar dari sekitar dan bertumbuh',
    theme: 'Air Terjun Kejernihan',
    islandName: 'Kuil Umpan Balik',
    meetingPhase: 2,
    color: 'indigo',
    badgeName: 'Hati Terbuka',
    badgeIcon: 'ShieldCheck',
    missionDescription:
      'Pilah masukan dari guru, teman, atau keluarga menjadi hal yang membangun dan menjatuhkan, lalu tentukan respons barumu.',
    motivationalQuote: 'Kritik bukan penilaian harga dirimu, melainkan petunjuk arah menuju karya yang lebih baik.',
    fields: [
      {
        id: 'received_criticism',
        label: 'Masukan yang pernah saya terima dari guru, teman, atau keluarga:',
        type: 'textarea',
        placeholder: 'Tuliskan masukan atau kritik yang pernah kamu terima...',
      },
      {
        id: 'constructive_aspect',
        sectionHeader: 'Evaluasi masukan tersebut:',
        label: 'Membangun:',
        type: 'textarea',
        placeholder: 'Bagian apa yang membangun atau memberi pelajaran berharga...',
      },
      {
        id: 'destructive_aspect',
        label: 'Menjatuhkan:',
        type: 'textarea',
        placeholder: 'Bagian apa yang terasa menjatuhkan atau kurang tepat...',
      },
      {
        id: 'what_i_improve',
        label: 'Yang saya ambil dan saya perbaiki:',
        type: 'textarea',
        placeholder: 'Poin perbaikan konkret yang kamu jalani...',
      },
      {
        id: 'response_strategy',
        label: 'Mulai sekarang, saya merespons kritik dengan cara:',
        type: 'textarea',
        placeholder: 'Sikap atau caramu merespons kritik di masa depan...',
      },
    ],
  },
  {
    id: 6,
    title: 'Belajar dari orang lain',
    subtitle: '(tokoh, guru, kakak kelas, teman, keluarga)',
    sectionTag: 'Success of others',
    etapeNumber: 2,
    etapeTitle: 'Etape 2: Belajar dari sekitar dan bertumbuh',
    theme: 'Desa Para Sahabat Bijak',
    islandName: 'Pustaka Inspirasi',
    meetingPhase: 2,
    color: 'violet',
    badgeName: 'Pembelajar Aktif',
    badgeIcon: 'Users',
    missionDescription:
      'Amati sosok yang kamu kagumi keberaniannya dan ambil satu kebiasaan yang bisa kamu tiru minggu ini.',
    motivationalQuote:
      'Keberhasilan orang lain bukan ukuran kegagalan saya. Itu bukti bahwa hal itu bisa dicapai.',
    reminderText:
      'Keberhasilan orang lain bukan ukuran kegagalan saya. Itu bukti bahwa hal itu bisa dicapai.',
    fields: [
      {
        id: 'admired_figure',
        label: 'Siapa yang saya kagumi keberaniannya, dan siapa dia bagi saya?',
        type: 'textarea',
        placeholder: 'Sebutkan nama dan hubungannya (tokoh, guru, kakak kelas, teman, atau keluarga)...',
      },
      {
        id: 'confidence_actions',
        label: 'Apa yang ia lakukan sehingga terlihat percaya diri?',
        type: 'textarea',
        placeholder: 'Tuliskan hal konkret yang ia lakukan...',
      },
      {
        id: 'imitation_action',
        label: 'Satu hal darinya yang bisa saya tiru minggu ini:',
        type: 'textarea',
        placeholder: 'Tindakan nyata yang akan kamu coba tiru...',
      },
    ],
  },
  {
    id: 7,
    title: 'Melihat kembali usaha saya',
    subtitle: 'Refleksi',
    sectionTag: 'Refleksi',
    etapeNumber: 2,
    etapeTitle: 'Etape 2: Belajar dari sekitar dan bertumbuh',
    theme: 'Cermin Keheningan Bintang',
    islandName: 'Menara Refleksi',
    meetingPhase: 2,
    color: 'purple',
    badgeName: 'Penghargai Proses',
    badgeIcon: 'Sparkles',
    missionDescription:
      'Setelah mencoba langkahmu selama satu minggu, refleksikan apa yang sudah berhasil dan bagian yang perlu diperbaiki.',
    motivationalQuote: PEGANGAN_DI_SEPANJANG_JALAN,
    fields: [
      {
        id: 'what_succeeded',
        label: 'Setelah mencoba langkah saya, apa yang sudah berhasil?',
        type: 'textarea',
        placeholder: 'Tuliskan pencapaian yang berhasil kamu lakukan...',
      },
      {
        id: 'what_failed_and_why',
        label: 'Bagian mana yang masih kurang berhasil, dan mengapa?',
        type: 'textarea',
        placeholder: 'Evaluasi bagian yang belum berjalan sesuai rencana...',
      },
      {
        id: 'new_self_knowledge',
        label: 'Hal baru yang saya ketahui tentang diri saya:',
        type: 'textarea',
        placeholder: 'Wawasan atau fakta baru mengenai dirimu...',
      },
      {
        id: 'felt_changes',
        label: 'Perubahan kecil yang sudah saya rasakan:',
        type: 'textarea',
        placeholder: 'Perubahan positif pada cara berpikir atau perasaanmu...',
      },
    ],
  },
  {
    id: 8,
    title: 'Komitmen dan target saya',
    subtitle: 'Garis akhir',
    sectionTag: 'Garis akhir',
    etapeNumber: 2,
    etapeTitle: 'Etape 2: Belajar dari sekitar dan bertumbuh',
    theme: 'Kuil Penobatan Juara',
    islandName: 'Puncak Growth Mindset',
    meetingPhase: 2,
    color: 'amber',
    badgeName: 'Growth Master',
    badgeIcon: 'Award',
    missionDescription:
      'Tetapkan target satu minggu ke depan, ukur keyakinanmu, dan nyatakan komitmen perubahan diri.',
    motivationalQuote: PESAN_UNTUK_DIRI_SAYA,
    fields: [
      {
        id: 'target_week_1',
        sectionHeader: 'Target satu minggu ke depan:',
        label: 'Target 1:',
        type: 'text',
        placeholder: 'Target konkret 1...',
      },
      {
        id: 'target_week_2',
        label: 'Target 2:',
        type: 'text',
        placeholder: 'Target konkret 2...',
      },
      {
        id: 'target_week_3',
        label: 'Target 3:',
        type: 'text',
        placeholder: 'Target konkret 3...',
      },
      {
        id: 'future_confidence_scale',
        label: 'Keyakinan saya terhadap perubahan diri saya berada pada angka:',
        type: 'slider',
        min: 1,
        max: 5,
        step: 1,
        minLabel: 'Belum yakin',
        maxLabel: 'Sangat yakin',
        helperText: 'Skala 1 (Belum yakin) sampai 5 (Sangat yakin)',
      },
      {
        id: 'final_commitment',
        label: 'Saya berkomitmen untuk:',
        type: 'textarea',
        placeholder: 'Tuliskan ikrar komitmen kesungguhanmu...',
      },
    ],
  },
];

export const DEFAULT_ADMIN: AdminCredentials = {
  username: 'admin',
  password: 'admin123',
  name: 'Guru Pembimbing BK',
};

export const INITIAL_STUDENTS: ActiveStudent[] = [
  {
    id: 'student-1',
    name: 'Budi Santoso',
    class: 'X-1',
    startedAt: '2026-09-15 08:00',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'student-2',
    name: 'Siti Rahma',
    class: 'X-1',
    startedAt: '2026-09-10 08:30',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'student-3',
    name: 'Dimas Pratama',
    class: 'X-2',
    startedAt: '2026-09-18 09:00',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80',
  },
  {
    id: 'student-4',
    name: 'Aisyah Putri',
    class: 'X-2',
    startedAt: '2026-09-18 09:45',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=120&q=80',
  },
];

export const INITIAL_JOURNEYS: Record<string, StudentJourney> = {
  'student-1': {
    studentId: 'student-1',
    studentName: 'Budi Santoso',
    studentClass: 'X-1',
    confidenceScore: 80,
    lastActiveStage: 4,
    updatedAt: '2026-09-17 14:00',
    stages: {
      1: {
        completed: true,
        completedAt: '2026-09-15 08:30',
        answers: {
          situation: 'Saat guru memanggil nama saya untuk membacakan jawaban soal di depan kelas.',
          thought: 'Bagaimana kalau jawaban saya salah dan teman-teman menertawakan saya.',
          feeling: 'Jantung berdegup kencang, telapak tangan dingin, dan tenggorokan tercekat.',
          action: 'Hanya diam menunduk dan pura-pura masih mencari buku catatan.',
          confidence_scale: 2,
        },
      },
      2: {
        completed: true,
        completedAt: '2026-09-16 10:15',
        answers: {
          challenge_target: 'Mengangkat tangan dan menjawab minimal 1 pertanyaan guru setiap pelajaran.',
          heavy_reason: 'Takut salah berbicara dan merasa belum sepintar teman lainnya.',
          growth_learning_way: 'Mencatat poin jawaban di kertas kecil terlebih dahulu sebelum menjawab.',
          fear_motto: 'Salah jawab bukan dosa, tapi bukti saya berani belajar!',
        },
      },
      3: {
        completed: true,
        completedAt: '2026-09-17 14:00',
        answers: {
          internal_obstacles: 'Pikiran overthinking dan rasa ragu sebelum bertindak.',
          external_obstacles: 'Suasana kelas yang terkadang menyoraki jika ada teman salah bicara.',
          why_obstacle_arises: 'Karena terlalu memikirkan pandangan orang lain dibanding proses belajar sendiri.',
          how_to_overcome: 'Tarik nafas dalam 3 hitungan dan fokus pada isi jawaban, bukan pada orang lain.',
          giveup_motto: 'Kalau saya berhenti sekarang, saya tidak akan pernah tahu seberapa jauh saya bisa bertumbuh.',
        },
      },
    },
  },
  'student-2': {
    studentId: 'student-2',
    studentName: 'Siti Rahma',
    studentClass: 'X-1',
    confidenceScore: 100,
    lastActiveStage: 8,
    updatedAt: '2026-09-18 11:20',
    driveExportedUrl: 'https://drive.google.com/drive/folders/growth-mindset-journey/X-1/Siti_Rahma.png',
    driveExportedAt: '2026-09-18 11:20',
    stages: {
      1: {
        completed: true,
        completedAt: '2026-09-10 09:00',
        answers: {
          situation: 'Saat harus memulai dialog dalam bahasa Inggris.',
          thought: 'Grammar saya berantakan, pronunciation saya medok.',
          feeling: 'Malu dan cemas dinilai kurang pintar.',
          action: 'Memilih diam dan membiarkan teman lain yang berbicara.',
          confidence_scale: 2,
        },
      },
      2: {
        completed: true,
        completedAt: '2026-09-11 09:30',
        answers: {
          challenge_target: 'Berlatih berbicara bahasa Inggris 3 kalimat setiap hari.',
          heavy_reason: 'Kurang terbiasa dan kosakata masih terbatas.',
          growth_learning_way: 'Merekam suara sendiri di handphone dan mendengarkannya ulang.',
          fear_motto: 'Practice makes progress, not perfection.',
        },
      },
      3: {
        completed: true,
        completedAt: '2026-09-12 11:00',
        answers: {
          internal_obstacles: 'Rasa malu saat mendengar suara rekaman sendiri.',
          external_obstacles: 'Tidak banyak teman yang mau diajak latihan bersama.',
          why_obstacle_arises: 'Zona nyaman ingin selalu terlihat sudah sempurna.',
          how_to_overcome: 'Latihan mandiri di kamar dengan membaca keras artikel berita pendek.',
          giveup_motto: 'Kesalahan hari ini adalah bahan bakar kefasihan esok hari.',
        },
      },
      4: {
        completed: true,
        completedAt: '2026-09-13 13:00',
        answers: {
          step_1: 'Membaca 1 paragraf bahasa Inggris setiap pagi.',
          step_2: 'Mencatat 3 kosakata baru di buku saku.',
          step_3: 'Menyapa guru bahasa Inggris dengan salam bahasa Inggris saat berpapasan.',
          start_date: '14 September 2026',
          consistency_strategy: 'Menempelkan sticky note pengingat di cermin kamar.',
          helper_person: 'Ibu di rumah dan teman sebangku.',
          step_done_motto: 'Satu langkah kecil telah saya selesaikan dengan bangga!',
        },
      },
      5: {
        completed: true,
        completedAt: '2026-09-14 10:20',
        answers: {
          received_criticism: 'Guru bahasa Inggris mengatakan intonasi kalimat tanya saya masih datar.',
          constructive_aspect: 'Saya jadi tahu bahwa intonasi sangat penting dalam bahasa Inggris.',
          destructive_aspect: 'Awalnya merasa dianggap tidak bisa sama sekali.',
          what_i_improve: 'Mendengarkan contoh pengucapan di kamus online dan menirukan intonasinya.',
          response_strategy: 'Tersenyum, mengucapkan terima kasih atas masukannya, dan langsung mencatatnya.',
        },
      },
      6: {
        completed: true,
        completedAt: '2026-09-15 15:45',
        answers: {
          admired_figure: 'Kak Raisa, kakak kelas XI yang menjadi juara debat sekolah.',
          confidence_actions: 'Dia berdiri tegak, berbicara tanpa terburu-buru, dan berani menatap mata lawan bicara.',
          imitation_action: 'Berlatih berdiri tegak di depan cermin sebelum berbicara.',
        },
      },
      7: {
        completed: true,
        completedAt: '2026-09-16 16:30',
        answers: {
          what_succeeded: 'Berhasil membaca 5 artikel dan berani menyapa guru bahasa Inggris.',
          what_failed_and_why: 'Di hari Rabu sempat lupa menghafal kosakata karena kelelahan tugas kelompok.',
          new_self_knowledge: 'Ternyata saat saya mulai berbicara, rasa takutnya cepat hilang setelah 1 menit.',
          felt_changes: 'Merasa lebih tenang dan tidak lagi gemetar saat disuruh membaca di kelas.',
        },
      },
      8: {
        completed: true,
        completedAt: '2026-09-17 10:00',
        answers: {
          target_week_1: 'Mengikuti seleksi klub bahasa Inggris sekolah.',
          target_week_2: 'Berani mengajukan 1 pertanyaan dalam diskusi kelas.',
          target_week_3: 'Konsisten membaca 10 halaman buku setiap pekan.',
          future_confidence_scale: 5,
          final_commitment: 'Saya berkomitmen untuk menyambut setiap tantangan sebagai kesempatan bertumbuh.',
        },
      },
    },
  },
  'student-3': {
    studentId: 'student-3',
    studentName: 'Dimas Pratama',
    studentClass: 'X-2',
    confidenceScore: 40,
    lastActiveStage: 1,
    updatedAt: '2026-09-18 09:10',
    stages: {
      1: {
        completed: true,
        completedAt: '2026-09-18 09:10',
        answers: {
          situation: 'Saat harus memimpin diskusi kerja kelompok.',
          thought: 'Takut teman tidak mau mendengarkan pendapat saya.',
          feeling: 'Gelisah dan canggung.',
          action: 'Menyerahkan tugas ketua kelompok ke teman lain.',
          confidence_scale: 2,
        },
      },
    },
  },
  'student-4': {
    studentId: 'student-4',
    studentName: 'Aisyah Putri',
    studentClass: 'X-2',
    confidenceScore: 0,
    lastActiveStage: 1,
    updatedAt: '2026-09-18 09:45',
    stages: {},
  },
};
